from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

def create_presentation():
    prs = Presentation()

    # Title Slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "2026 全球記憶體產業供需與台股分析"
    subtitle.text = "AI 超級循環下的機遇與挑戰\nGenerated by OpenClaw"

    # Slide 2: 摘要
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "報告摘要"
    body_shape = slide.shapes.placeholders[1]
    tf = body_shape.text_frame
    tf.text = "1. AI 需求引爆「超級循環」，HBM 成為市場核心。"
    p = tf.add_paragraph()
    p.text = "2. 三大原廠產能轉移，導致傳統 DRAM/NAND 供給嚴重排擠。"
    p = tf.add_paragraph()
    p.text = "3. DDR4 價格出現反常溢價，2026 上半年報價預期暴漲。"
    p = tf.add_paragraph()
    p.text = "4. 台股記憶體族群短線修正，長線受惠轉單與漲價紅利。"

    # Slide 3: 產能排擠效應
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "核心驅動力：AI 產能排擠效應"
    body_shape = slide.shapes.placeholders[1]
    tf = body_shape.text_frame
    tf.text = "HBM 需求大爆發："
    p = tf.add_paragraph()
    p.text = "• 預估 2026 年需求年增率高達 70% 以上。"
    p = tf.add_paragraph()
    p.text = "晶圓消耗量驚人："
    p = tf.add_paragraph()
    p.text = "• 生產一顆 HBM，消耗的晶圓面積是傳統 DDR5 的三倍以上。"
    p = tf.add_paragraph()
    p.text = "引發供給失衡："
    p = tf.add_paragraph()
    p.text = "• 三星、SK海力士、美光將龐大產能轉往高毛利的 HBM，造成傳統記憶體出現供給真空。"

    # Slide 4: 台廠戰略機遇
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "台股供應鏈的長線機遇"
    body_shape = slide.shapes.placeholders[1]
    tf = body_shape.text_frame
    tf.text = "台廠的利基優勢："
    p = tf.add_paragraph()
    p.text = "• 南亞科、華邦電、旺宏專注於利基型與舊世代 DRAM/NAND (如 DDR3/DDR4)。"
    p = tf.add_paragraph()
    p.text = "承接國際大廠轉單與報價紅利："
    p = tf.add_paragraph()
    p.text = "• 原廠退出 DDR3/DDR4 市場，台廠成為供給短缺的唯一解方，享受罕見的漲價與溢價。"
    p = tf.add_paragraph()
    p.text = "結論與展望："
    p = tf.add_paragraph()
    p.text = "• 台股記憶體族群的短線震盪屬於技術與籌碼修正，整體產業超級週期預計至少延續至 2027 下半年。"

    prs.save('Memory_Industry_Report_2026.pptx')

if __name__ == '__main__':
    create_presentation()
    print("PPTX generated successfully.")
